<a href="https://colab.research.google.com/github/RaulGadirov/happy-sad-face-classifier/blob/main/face.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from PIL import Image
import os
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [3]:
directory = "/content/train/"

In [4]:
data = []
target =[]
for filename in os.listdir(directory):
  img = Image.open(directory+filename).convert('1')
  data.append(list(img.getdata()))
  a = filename.split("_")[0]
  if a=="happy":
    target.append([1,0])
  else:
    target.append([0,1])

In [5]:
data = np.array(data)
target = np.array(target)

In [6]:
data = data/255
for i in data:
  print(i)

[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]


In [7]:
for p in target:
  print(p)

[1 0]
[0 1]
[1 0]
[0 1]
[1 0]
[0 1]
[1 0]
[0 1]
[0 1]
[1 0]
[0 1]
[1 0]
[0 1]
[0 1]
[0 1]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]


In [8]:
data.shape

(20, 1024)

In [9]:
model = Sequential()
model.add(Dense(1024,input_dim=1024,activation='relu'))
model.add(Dense(512,activation='relu'))
model.add(Dense(256,activation="relu"))
model.add(Dense(128,activation="relu"))
model.add(Dense(2,activation="softmax"))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.compile(loss="categorical_crossentropy",optimizer=Adam(learning_rate=0.005),metrics=["accuracy"])

In [11]:
model.fit(data,target,epochs=1000,batch_size=32,verbose=1)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.5000 - loss: 0.6881
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 14.4221
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 22.5441
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.9521
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 10.1660
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 3.8950
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 3.5171
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 2.7476
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6950
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 1.4911
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.9298
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy

In [27]:
test = []
img_test = Image.open("/content/test/happy_test.png").convert('1')
test.append(list(img_test.getdata()))
test = np.array(test)/255
print(model.predict(test).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
[[1. 0.]]


In [28]:
test = []
img_test = Image.open("/content/test/sad_test.png").convert('1')
test.append(list(img_test.getdata()))
test = np.array(test)/255
print(model.predict(test).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[0. 1.]]
